batch_size: 16
height: 32
learning_rate: 0.0005
max_text_length: 21
model_path: Models/03_handwriting_recognition\202311060145
train_epochs: 100
train_workers: 20
vocab: UZ.K1b'2Nu7ge6MomJ5CH0/zD94h:*sPTq8QdY#L3jFB?IGfiWrRSy+(acpxn&VAv-lE",!wO)t;Xk
width: 128
