batch_size: 16
height: 32
learning_rate: 0.0005
max_text_length: 21
model_path: Models/03_handwriting_recognition/202311290145
train_epochs: 50
train_workers: 20
vocab: V.L?grB8nq4NW3JAe0b*ztOCZ"y:#d/X7w1YuS)If6coT,ikM'-2xRph9lFDK5vUHGmsEP;aj&(+Q!
width: 128
