batch_size: 16
height: 32
learning_rate: 0.0005
max_text_length: 21
model_path: Models/03_handwriting_recognition\202311300337
train_epochs: 20
train_workers: 20
vocab: peO37sDotW2Zc08HA-dBw1hl9&*b'FxLjPR+?CQ5iTuV)zrykEf,qKm4XN!G6/(nJaI.:Uv"Y#g;SM
width: 128
